/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-09-28 13:45:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Ds_005fAdmin.article;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Com.SysSetPackages.UserSetPackages.ProxyUserPackages.UserPurview;
import Com.SysSetPackages.UserSetPackages.ProxyUserPackages.ProxyUserPurview;
import Com.SharePackages.checkStr;
import Com.SharePackages.Field_Str;

public final class articleadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Ds_Admin/include/userproxy.jsp", Long.valueOf(1417490842773L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      Com.SharePackages.Str_code_switch tostr = null;
      tostr = (Com.SharePackages.Str_code_switch) _jspx_page_context.getAttribute("tostr", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (tostr == null){
        tostr = new Com.SharePackages.Str_code_switch();
        _jspx_page_context.setAttribute("tostr", tostr, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    String bid = tostr.to_utf_8 (request.getParameter ("bid"));
    String sid = tostr.to_utf_8 (request.getParameter ("sid"));
    UserPurview UserProxy = new ProxyUserPurview();
    String UserProxyStr = UserProxy.UserProxy (request);
    if (checkStr.isNull (UserProxyStr))
    {
        out.print("抱歉，您无权操作此模块");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>文章添加</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/Ds_Admin/css/web.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/");
      out.print(checkStr.Parame(request,2));
      out.write("/easyui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/icon.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/ajaxfileupload.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/validata.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/mask.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/xheditor/xheditor-1.2.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/xheditor/xheditor_lang/zh-cn.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("        //xbhEditor编辑器图片上传回调函数\r\n");
      out.write("        function insertUpload(msg) {\r\n");
      out.write("            var _msg = msg.toString();\r\n");
      out.write("            //var _picture_name = _msg.substring(_msg.lastIndexOf(\"/\") + 1);\r\n");
      out.write("            //var _picture_path = Substring(_msg);\r\n");
      out.write("            var _str = \"<div style='width:200px; float: left;text-align: center;border: 1px #cccccc solid;padding: 2px; margin-right: 5px;'>\" +\r\n");
      out.write("                    \"<div style='width:200px;margin-bottom: 5px;'><img src='\"+msg+\"' width='200'></div>\" +\r\n");
      out.write("                    \"<div style='width: 200px; height: 20px; text-align: center;'><input type='radio' name='pictures' id='pictures' onclick='RadioClick(this);' value='\" + msg + \"'/>设为封面</div>\" +\r\n");
      out.write("                    \"</div>\";\r\n");
      out.write("            $(\"#xh_editor\").append(_msg);\r\n");
      out.write("            //$(\"#uploadList\").append(_str);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //处理服务器返回到回调函数的字符串内容,格式是JSON的数据格式.\r\n");
      out.write("        function Substring(s) {\r\n");
      out.write("            return s.substring(s.substring(0, s.lastIndexOf(\"/\")).lastIndexOf(\"/\"), s.length);\r\n");
      out.write("        }\r\n");
      out.write("        $(function() {\r\n");
      out.write("            //初始化xhEditor编辑器插件  \r\n");
      out.write("            $('#xh_editor').xheditor({\r\n");
      out.write("                tools: 'full',\r\n");
      out.write("                skin: 'default',\r\n");
      out.write("                upMultiple: true,\r\n");
      out.write("                upImgUrl: \"/Action/XheditorLoad.do\",\r\n");
      out.write("                upImgExt: \"jpg,jpeg,gif,bmp,png\",\r\n");
      out.write("                onUpload: insertUpload,\r\n");
      out.write("                cleanPaste:3,\r\n");
      out.write("                html5Upload: false\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $('#save').bind(\"click\",function(){\r\n");
      out.write("                $('#form').form('submit', {\r\n");
      out.write("                    url:\"/Action/SysArticle.do\",\r\n");
      out.write("                    onSubmit: function(){\r\n");
      out.write("                        var flag = $(this).form('validate');\r\n");
      out.write("                        if (flag) {\r\n");
      out.write("                            if($(\"#xh_editor\").val()==\"\")\r\n");
      out.write("                            {\r\n");
      out.write("                                $.messager.alert('系统提示', '请输入文章内容', 'error');\r\n");
      out.write("                                flag=false;\r\n");
      out.write("                            }\r\n");
      out.write("                            else\r\n");
      out.write("                            {\r\n");
      out.write("                                $(\"#xh_editor\").value = $(\"#xh_editor\").val();\r\n");
      out.write("                                $.mask();\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        return flag;\r\n");
      out.write("                    },\r\n");
      out.write("                    success:function(msg){\r\n");
      out.write("                        $.mask.hide();\r\n");
      out.write("                        var jsondata = eval('(' + msg + ')');\r\n");
      out.write("                        if (jsondata.err == \"\")//表示没有出错\r\n");
      out.write("                        {\r\n");
      out.write("                            $(window.parent.$('#gd').window('close'));\r\n");
      out.write("                            $(window.parent.$.messager.alert('系统提示', jsondata.msg, 'info'));\r\n");
      out.write("                            $(window.parent.$(\"#ArtList\").datagrid('reload'));\r\n");
      out.write("                        }\r\n");
      out.write("                        else {\r\n");
      out.write("                            $.messager.alert('系统提示', jsondata.err, 'error');\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("<div region=\"north\" style=\"height:31px;overflow:hidden;\" split=\"false\" border=\"false\">\r\n");
      out.write("    <div class=\"datagrid-toolbar\">\r\n");
      out.write("        <a id=\"save\" icon=\"icon-save\" href=\"javascript:void('');\" onclick=\"save();\" class=\"easyui-linkbutton\"\r\n");
      out.write("           plain=\"true\">保存</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div region=\"center\" style=\"padding:5px;\" border=\"false\">\r\n");
      out.write("    <form id=\"form\" method=\"post\">\r\n");
      out.write("        <table class=\"table-edit\" width=\"98%\" align=\"center\">\r\n");
      out.write("            <tr class=\"title\"><td colspan=\"2\">文章信息</td></tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"width:8%;text-align: right;\">文章分类:</td>\r\n");
      out.write("                <td style=\"line-height: 18px;\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"artmethod\" value=\"add\"/>\r\n");
      out.write("                    <input type=\"hidden\" value=\"");
      out.print(bid);
      out.write("\" name=\"bid\"/>\r\n");
      out.write("                    <input type=\"hidden\" value=\"");
      out.print(sid);
      out.write("\" name=\"sid\"/>\r\n");
      out.write("                    <select id=\"cateid\" name=\"cateid\" class=\"easyui-combobox\"\r\n");
      out.write("                            style=\"width: 150px;*width: 155px;\"\r\n");
      out.write("                            data-options=\"required:false,\r\n");
      out.write("                            editable:false\">\r\n");
      out.write("                        ");

                            for(int i=0;i< Field_Str.ArticleType.length;i++)
                            {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(Field_Str.ArticleType[i]);
      out.write("</option>\r\n");
      out.write("                        ");

                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"text-align: right;\">文章标题:</td>\r\n");
      out.write("                <td style=\"width:92%;\">\r\n");
      out.write("                    <input type=\"text\" name=\"title\" id=\"title\"\r\n");
      out.write("                           class=\"easyui-validatebox\"\r\n");
      out.write("                           data-options=\"required:true,validType:'length[2,20]',\r\n");
      out.write("                           invalidMessage:'不能少于2个汉字',\r\n");
      out.write("                           missingMessage:'请至少输入2个汉字'\"\r\n");
      out.write("                           style=\"width:600px;\"\r\n");
      out.write("                           maxlength=\"50\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"text-align: right;\">文章内容:</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <textarea id=\"xh_editor\" name=\"xh_editor\"\r\n");
      out.write("                                          style=\"width:100%; height: 400px; border: 1px\"></textarea>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"text-align: right;\">是否审核:</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select id=\"islock\" name=\"islock\" class=\"easyui-combobox\"\r\n");
      out.write("                            style=\"width: 150px;*width: 155px;\"\r\n");
      out.write("                            data-options=\"required:false,\r\n");
      out.write("                            editable:false,panelHeight:40,\">\r\n");
      out.write("                        <option value=\"0\">正常</option>\r\n");
      out.write("                        <option value=\"1\">锁定</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"text-align: right;\">文章状态:</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select id=\"status\" name=\"status\" class=\"easyui-combobox\"\r\n");
      out.write("                            style=\"width: 150px;*width: 155px;\"\r\n");
      out.write("                            data-options=\"required:false,\r\n");
      out.write("                            editable:false,panelHeight:40,\">\r\n");
      out.write("                        <option value=\"0\">正常</option>\r\n");
      out.write("                        <option value=\"1\">推荐</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
