/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-09-27 13:16:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.download;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sitehome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/include/left.jsp", Long.valueOf(1443359240855L));
    _jspx_dependants.put("/include/top.jsp", Long.valueOf(1443359749058L));
    _jspx_dependants.put("/include/foot.jsp", Long.valueOf(1443359240835L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"/www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("<title>渔人游戏－好玩的棋牌电玩游戏平台</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"渔人棋牌游戏,捕鱼,斗地主,梭哈,金花,水果机\"/>\r\n");
      out.write("<meta name=\"description\" content=\"信誉棋牌游戏,真正赚金的游戏-渔人。\"/>\r\n");
      out.write("    <link type=\"image/gif\" rel=\"icon\" title=\"\" href=\"/images/animated_favicon1.gif\"/>\r\n");
      out.write("    <link href=\"/style1/css.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/jcarousellite_1.0.1.js\"></script></head>\r\n");
      out.write("<body> \r\n");
      out.write("<!--头部开始-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"head\">\r\n");
      out.write("    <div class=\"topbar\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <a href=\"/\" title=\"渔人\"><img src=\"/images/logo.png\" alt=\"渔人\" border=\"0\"/></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sideBar\">\r\n");
      out.write("            <div class=\"user\">\r\n");
      out.write("                <a href=\"#\" class=\"login\">账号登陆</a><a href=\"/reg/gamereg\">注册帐号</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"top_menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li class=\"curr\"><a href=\"index.html\">网站首页</a></li>\r\n");
      out.write("            <li><a href=\"mindex.html\">用户中心</a></li>\r\n");
      out.write("            <li><a href=\"download.html\">游戏下载</a></li>\r\n");
      out.write("            <li><a href=\"PayOnline.html\">充值中心</a></li>\r\n");
      out.write("            <!--<li><a href=\"Popularize.html\">玩家推广</a></li>\r\n");
      out.write("            <li><a href=\"Roulette.html\">幸运抽奖</a></li>-->\r\n");
      out.write("            <li><a href=\"news.html\">棋牌资讯</a></li>\r\n");
      out.write("            <li><a href=\"aqlist.html\">帮助中心</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!--头部结束-->\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<div class=\"common_left\">\r\n");
      out.write("    <!--左侧通用开始-->\r\n");
      out.write("    <div class=\"shortcut-box\">\r\n");
      out.write("        <div class=\"download\">\r\n");
      out.write("            <a href=\"/download\"><strong>游戏大厅下载</strong>\r\n");
      out.write("                <p>\r\n");
      out.write("                    版本号：15.09.01 软件大小：3.70M<br/>\r\n");
      out.write("                    发布时间：2015/09/01\r\n");
      out.write("                </p>\r\n");
      out.write("                <span>本游戏适合18岁以上的玩家</span></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"reg\">\r\n");
      out.write("            <a href=\"reg.html\">立即注册</a>\t\t  </div>\r\n");
      out.write("        <div class=\"recharge\">\r\n");
      out.write("            <a href=\"payonline.html\">账户充值</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container1 p20\">\r\n");
      out.write("        <div class=\"tt\">\r\n");
      out.write("            <a href=\"aqlist.html\"></a><span>常见问题</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <ul class=\"li1\">\r\n");
      out.write("                <li><a href=\"aqview.html\">这里是标题</a></li>\r\n");
      out.write("                <li><a href=\"aqview.html\">这里是标题</a></li>\r\n");
      out.write("                <li><a href=\"aqview.html\">这里是标题</a></li>\r\n");
      out.write("                <li><a href=\"aqview.html\">这里是标题</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"service p20\">\r\n");
      out.write("        <a target=\"_blank\" href=\"http://wpa.qq.com/msgrd?v=3&uin=10057357&site=qq&menu=yes\"><img border=\"0\" src=\"/images/qq.gif\" alt=\"点击这里给我发消息\" title=\"点击这里给我发消息\"></a>\r\n");
      out.write("        <div class=\"remove\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--左侧通用结束-->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"main_right\">\r\n");
      out.write("    <div class=\"main_box\">\r\n");
      out.write("      <div class=\"location\"><span><p>游戏下载</p></span>\r\n");
      out.write("        <div class=\"en\">\r\n");
      out.write("       <!--当前位置-->\r\n");
      out.write("        <span>您的位置：渔人棋牌 &gt; 游戏下载</span>\r\n");
      out.write("        <!--当前位置结束-->\r\n");
      out.write("        Game download</div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      <div class=\"gamelist\">\r\n");
      out.write("        <!--游戏大厅下载开始-->\r\n");
      out.write("        <div class=\"game_lobby\">\r\n");
      out.write("          <div class=\"name\">渔人棋牌游戏大厅</div>\r\n");
      out.write("          <div class=\"text\">精简大厅：<strong>3.70</strong>M <br>\r\n");
      out.write("完整大厅：<strong>113.00</strong>M<br>\r\n");
      out.write("更新日期：<strong>2015/09/01</strong><br></div>\r\n");
      out.write("          <div class=\"down\"><a href=\"#\" target=\"_blank\" class=\"d1\">完整版下载</a> <a href=\"#\" target=\"_blank\" class=\"d2\">精简版下载</a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!--游戏大厅下载结束-->\r\n");
      out.write("        <div class=\"game_list\">\r\n");
      out.write("          <ul>\r\n");
      out.write("          <!--热门游戏内容循环开始-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!--热门游戏内容循环结束-->\r\n");
      out.write("            <div class=\"remove\"></div>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <div class=\"remove\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"remove\"></div>\r\n");
      out.write("  \r\n");
      out.write("  </div>\r\n");
      out.write("<!--底部开始-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"foot\">\r\n");
      out.write("    <div class=\"box\">\r\n");
      out.write("        <div class=\"bottom_logo\">\r\n");
      out.write("            <img src=\"/images/bottom_logo.png\" alt=\"最好玩的棋牌平台\" width=\"158\" height=\"72\"/>\t\t</div>\r\n");
      out.write("        <div class=\"copyright\">\r\n");
      out.write("            健康游戏公告：抵制不良游戏 拒绝盗版游戏 注意自我保护 谨防受骗上当 适度游戏益脑 沉迷游戏伤身 合理安排时间 享受健康生活<br/>\r\n");
      out.write("            禁止任何利用本平台游戏进行赌博的行为，让我们共同净化游戏环境，一旦发现有违反用户协议的行为，我们将会冻结此玩家账号\r\n");
      out.write("            <br/>\r\n");
      out.write("            Copyright © 2015 Www.jiaqp.Com Asiasoft Inc.All Rights Reserved\r\n");
      out.write("            <a href=\"http://www.jiaqp.com\">渔人游戏中心</a> 版权所有 浙网文[2015]0342-112号 浙B2-20080029\t\t</div>\r\n");
      out.write("        <div class=\"remove\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--底部结束-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
