/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2016-01-11 03:10:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Com.ArticlePackages.Article_Pro;
import Com.ArticlePackages.SingleArticle;
import Com.SharePackages.Field_Str;
import Com.SharePackages.checkStr;
import java.util.Iterator;

public final class reg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/include/left.jsp", Long.valueOf(1443617340522L));
    _jspx_dependants.put("/include/top.jsp", Long.valueOf(1443448803668L));
    _jspx_dependants.put("/include/foot.jsp", Long.valueOf(1443359240835L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"/www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("<title>用户注册－我想游游戏－好玩的棋牌电玩游戏平台</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"渔人棋牌游戏,捕鱼,斗地主,梭哈,金花,水果机\"/>\r\n");
      out.write("<meta name=\"description\" content=\"信誉棋牌游戏,真正赚金的游戏-渔人。\"/>\r\n");
      out.write("    <link href=\"/style1/css.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/Common.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $(document).ready(\r\n");
      out.write("                function(){\r\n");
      out.write("                    var loginmsg=\"\",nickmsg=\"\";\r\n");
      out.write("                    $(\"#txtAccounts\").blur(function(){\r\n");
      out.write("                        if(GetByteLength($.trim($(\"#txtAccounts\").val()))>20 ||\r\n");
      out.write("                                GetByteLength($.trim($(\"#txtAccounts\").val()))<6)\r\n");
      out.write("                        {\r\n");
      out.write("                            loginmsg=\"{'err':'用户名长度只能在6-20个字符之间','msg':''}\";\r\n");
      out.write("                            $(\"#txtAccountsTip\").html(\"用户名长度只能在6-20个字符之间\");\r\n");
      out.write("                        }\r\n");
      out.write("                        else\r\n");
      out.write("                        {\r\n");
      out.write("                            //进行用户名重复的验证\r\n");
      out.write("                            $.ajax({\r\n");
      out.write("                                type:\"POST\",\r\n");
      out.write("                                url:\"/Member/RegAction.do\",\r\n");
      out.write("                                data:\"regmethod=valiloginname&loginname=\"+$.trim($(\"#txtAccounts\").val()),\r\n");
      out.write("                                async: true,\r\n");
      out.write("                                beforeSend:function(){\r\n");
      out.write("                                    $(\"#txtAccountsTip\").html(\"正在验证...\");\r\n");
      out.write("                                },//执行ajax前执行loading函数.直到success\r\n");
      out.write("                                success:function(msg){\r\n");
      out.write("                                    loginmsg=msg;\r\n");
      out.write("                                    var jsondata = eval('(' + msg + ')');\r\n");
      out.write("                                    if(jsondata.err == \"\")//表示没有出错\r\n");
      out.write("                                    {\r\n");
      out.write("                                        $(\"#txtAccountsTip\").html(\"用户名可以使用\");\r\n");
      out.write("                                    }\r\n");
      out.write("                                    else\r\n");
      out.write("                                    {\r\n");
      out.write("                                        $(\"#txtAccountsTip\").html(\"用户名已被占用\");\r\n");
      out.write("                                    }\r\n");
      out.write("                                } //成功时执行Response函数\r\n");
      out.write("                            });\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                    $(\"#txtNickname\").blur(function(){\r\n");
      out.write("                        //用户称昵验证\r\n");
      out.write("                        if($.trim($(\"#txtNickname\").val()).length<3 || $.trim($(\"#txtNickname\").val()).length>8)\r\n");
      out.write("                        {\r\n");
      out.write("                            nickmsg={'err':'游戏称昵长度只能是3-8个字符或汉字之间','msg':''};\r\n");
      out.write("                            $(\"#txtNicknameTip\").html(\"游戏称昵长度只能是3-8个字符或汉字之间\");\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        else\r\n");
      out.write("                        {\r\n");
      out.write("                            //进行称昵重复的验证\r\n");
      out.write("                            $.ajax({\r\n");
      out.write("                                type:\"POST\",\r\n");
      out.write("                                url:\"/Member/RegAction.do\",\r\n");
      out.write("                                data:\"regmethod=valinick&nick=\"+$.trim($(\"#txtNickname\").val()),\r\n");
      out.write("                                async: true,\r\n");
      out.write("                                beforeSend:function(){\r\n");
      out.write("                                    $(\"#txtNicknameTip\").html(\"正在验证...\");\r\n");
      out.write("                                },//执行ajax前执行loading函数.直到success\r\n");
      out.write("                                success:function(msg){\r\n");
      out.write("                                    nickmsg=msg;\r\n");
      out.write("                                    var jsondata = eval('(' + msg + ')');\r\n");
      out.write("                                    if(jsondata.err == \"\")//表示没有出错\r\n");
      out.write("                                    {\r\n");
      out.write("                                        $(\"#txtNicknameTip\").html(\"称昵可以使用\");\r\n");
      out.write("                                    }\r\n");
      out.write("                                    else\r\n");
      out.write("                                    {\r\n");
      out.write("                                        $(\"#txtNicknameTip\").html(\"称昵已被占用\");\r\n");
      out.write("                                    }\r\n");
      out.write("                                } //成功时执行Response函数\r\n");
      out.write("                            });\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                    $(\"#btnRegister\").bind(\"click\",function(){\r\n");
      out.write("                        if($(\"#txtAccounts\").val()==\"\")\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtAccountsTip\").html(\"请输入用户名\");\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        if($(\"#txtNickname\").val()==\"\")\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtNicknameTip\").html(\"请输入称昵\");\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        if(eval('(' + loginmsg + ')').err!=\"\")\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtAccountsTip\").html(eval('(' + loginmsg + ')').err);\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        else\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtAccountsTip\").html(eval('(' + loginmsg + ')').msg);\r\n");
      out.write("                        }\r\n");
      out.write("                        if(eval('(' + nickmsg + ')').err!=\"\")\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtNicknameTip\").html(eval('(' + nickmsg + ')').err);\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        else\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtNicknameTip\").html(eval('(' + nickmsg + ')').msg);\r\n");
      out.write("                        }\r\n");
      out.write("                        //姓别验证\r\n");
      out.write("                        if($('input:radio[name=\"txtSex\"]:checked').val()==null)\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtSexTip\").html(\"请选择性别\");\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        else\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtSexTip\").html(\"\");\r\n");
      out.write("                        }\r\n");
      out.write("                        //用户密码验证\r\n");
      out.write("                        if($.trim($(\"#txtLogonPass\").val()).length<6 || $.trim($(\"#txtLogonPass\").val()).length>20)\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtLogonPassTip\").html(\"不能使用过于简单的密码\");\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        else\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtLogonPassTip\").html(\"\");\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        //检测二次密码输入是否一致\r\n");
      out.write("                        if($.trim($(\"#txtLogonPass\").val())!=$.trim($(\"#txtLogonPass2\").val()))\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtLogonPass2Tip\").html(\"两次密码输入不一致\");\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        else\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtLogonPass2Tip\").html(\"\");\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("                        //用户银行密码验证\r\n");
      out.write("                        if(!CheckEmail($.trim($(\"#txtInsureEmail\").val())))\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtInsureEmailTip\").html(\"请输入有效的邮箱\");\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        else\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#txtInsureEmailTip\").html(\"\");\r\n");
      out.write("                        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        //服务条款check框\r\n");
      out.write("                        if(!$(\"#chk_agree\").attr(\"checked\"))\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#id_agree\").html(\"请选择注册条款\");\r\n");
      out.write("                            return;\r\n");
      out.write("                        }\r\n");
      out.write("                        else\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#id_agree\").html(\"\");\r\n");
      out.write("                        }\r\n");
      out.write("                        if(loginmsg!=\"\" && nickmsg!=\"\")\r\n");
      out.write("                        {\r\n");
      out.write("                            $(\"#btnRegister\").attr({\"disabled\":\"disabled\"});\r\n");
      out.write("                            $(\"#regform\").submit();\r\n");
      out.write("                        }\r\n");
      out.write("                        else\r\n");
      out.write("                        {\r\n");
      out.write("                            alert(\"抱歉，无法获取信息，注册失败\");\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("                });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!--头部开始-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"head\">\r\n");
      out.write("    <div class=\"topbar\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <a href=\"/\" title=\"渔人\"><img src=\"/images/logo.png\" alt=\"渔人\" border=\"0\"/></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sideBar\">\r\n");
      out.write("            <div class=\"user\">\r\n");
      out.write("                <a href=\"#\" class=\"login\">账号登陆</a><a href=\"/reg/gamereg\">注册帐号</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"top_menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li class=\"curr\"><a href=\"/\">网站首页</a></li>\r\n");
      out.write("            <li><a href=\"#\">用户中心</a></li>\r\n");
      out.write("            <li><a href=\"/download\">游戏下载</a></li>\r\n");
      out.write("            <li><a href=\"#\">充值中心</a></li>\r\n");
      out.write("            <!--<li><a href=\"Popularize.html\">玩家推广</a></li>\r\n");
      out.write("            <li><a href=\"Roulette.html\">幸运抽奖</a></li>-->\r\n");
      out.write("            <li><a href=\"/news/list/cate/0\">棋牌资讯</a></li>\r\n");
      out.write("            <li><a href=\"/news/help/cate/1\">帮助中心</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!--头部结束-->\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<div class=\"common_left\">\r\n");
      out.write("    <!--左侧通用开始-->\r\n");
      out.write("    <div class=\"shortcut-box\">\r\n");
      out.write("        <div class=\"download\">\r\n");
      out.write("            <a href=\"/download\"><strong>游戏大厅下载</strong>\r\n");
      out.write("                <p>\r\n");
      out.write("                    版本号：15.09.01 软件大小：3.70M<br/>\r\n");
      out.write("                    发布时间：2015/09/01\r\n");
      out.write("                </p>\r\n");
      out.write("                <span>本游戏适合18岁以上的玩家</span></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"reg\">\r\n");
      out.write("            <a href=\"/reg/gamereg\">立即注册</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"recharge\">\r\n");
      out.write("            <a href=#\">账户充值</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container1 p20\">\r\n");
      out.write("        <div class=\"tt\">\r\n");
      out.write("            <span>常见问题</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <ul class=\"li1\">\r\n");
      out.write("                ");

                    Iterator QuaIt=SingleArticle.getInstance().getArticleDb().ArticleList("",
                            "4","*","article a",
                            "a.*","a.cateid=1 and a.islock=0",
                            "a.articleid","desc").iterator();
                    while (QuaIt.hasNext())
                    {
                        Article_Pro quapro=(Article_Pro)QuaIt.next();
                        if(quapro!=null)
                        {
                
      out.write("\r\n");
      out.write("                <li><a href=\"/news/article/id/");
      out.print(quapro.getCateid());
      out.write('/');
      out.print(quapro.getArticleid());
      out.write('"');
      out.write('>');
      out.print(quapro.getArticletitle());
      out.write("</a></li>\r\n");
      out.write("                ");

                        }
                        QuaIt.remove();
                    }
                
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"service p20\">\r\n");
      out.write("        <a target=\"_blank\" href=\"http://wpa.qq.com/msgrd?v=3&uin=10057357&site=qq&menu=yes\"><img border=\"0\" src=\"/images/qq.gif\" alt=\"点击这里给我发消息\" title=\"点击这里给我发消息\"></a>\r\n");
      out.write("        <div class=\"remove\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--左侧通用结束-->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"main_right\">\r\n");
      out.write("    <div class=\"main_box\">\r\n");
      out.write("      <div class=\"location\"><span>\r\n");
      out.write("      <p>会员注册</p>\r\n");
      out.write("      </span>\r\n");
      out.write("        <div class=\"en\">\r\n");
      out.write("       <!--当前位置-->\r\n");
      out.write("       Register</div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"login_box\">\r\n");
      out.write("          <form method=\"post\" id=\"regform\" action=\"/Member/RegAction.do\" onsubmit=\"return false;\">\r\n");
      out.write("          <ul>\r\n");
      out.write("          <LI>\r\n");
      out.write("            <span class=\"span1\">用户名：</span>\r\n");
      out.write("            <span class=\"span2\"><input type=\"text\" name=\"txtAccounts\" id=\"txtAccounts\" maxlength=\"10\" style=\"line-height:30px; height:30px; width:250px; border: solid 1px #cfcfcf\"></span>\r\n");
      out.write("              <span class=\"span3\" id=\"txtAccountsTip\">由6-20位字符组成，中文算2个字符</span>\r\n");
      out.write("          </LI>\r\n");
      out.write("          <LI>\r\n");
      out.write("            <span class=\"span1\">昵称：</span>\r\n");
      out.write("            <span class=\"span2\"><input type=\"text\" name=\"txtNickname\" maxlength=\"8\" id=\"txtNickname\" style=\"line-height:30px; height:30px; width:250px; border:  solid 1px #cfcfcf\"></span>\r\n");
      out.write("            <span class=\"span3\"><span id=\"txtNicknameTip\">由3-8位字符或汉字之间</span></span>\r\n");
      out.write("            </LI>\r\n");
      out.write("          <LI>\r\n");
      out.write("            <span class=\"span1\">性别：</span>\r\n");
      out.write("            <span class=\"span2\" style=\"padding-top: 5px;\"><input type=\"radio\" name=\"txtSex\" value=\"0\">男\r\n");
      out.write("            <input type=\"radio\" name=\"txtSex\" value=\"1\">女</span>\r\n");
      out.write("              <span class=\"span3\" id=\"txtSexTip\">请选择性别</span>\r\n");
      out.write("</LI>\r\n");
      out.write("          <LI>\r\n");
      out.write("            <span class=\"span1\">密码：</span>\r\n");
      out.write("                <span class=\"span2\"><input type=\"password\" name=\"txtLogonPass\" id=\"txtLogonPass\" maxlength=\"20\" style=\"line-height:30px; height:30px; width:250px; border:  solid 1px #cfcfcf\"></span>\r\n");
      out.write("                <span class=\"span3\" id=\"txtLogonPassTip\">由6-20位字符组成</span>\r\n");
      out.write("            </LI>\r\n");
      out.write("          <LI>\r\n");
      out.write("            <span class=\"span1\">确认密码：</span>\r\n");
      out.write("              <span class=\"span2\"><input type=\"password\" name=\"txtLogonPass2\" id=\"txtLogonPass2\" maxlength=\"20\" style=\"line-height:30px; height:30px; width:250px; border:  solid 1px #cfcfcf\"></span>\r\n");
      out.write("              <span class=\"span3\" id=\"txtLogonPass2Tip\">请再次输入密码</span>\r\n");
      out.write("            </LI>\r\n");
      out.write("          <LI>\r\n");
      out.write("              <span class=\"span1\">邮箱：</span>\r\n");
      out.write("              <span class=\"span2\"><input type=\"text\" name=\"txtInsureEmail\" id=\"txtInsureEmail\" maxlength=\"30\" style=\"line-height:30px; height:30px; width:250px; border:  solid 1px #cfcfcf\"></span>\r\n");
      out.write("              <span class=\"span3\" id=\"txtInsureEmailTip\">用于找回密码之用</span>\r\n");
      out.write("            </LI>\r\n");
      out.write("          <LI><span class=\"span1\">推荐人ID：</span>\r\n");
      out.write("            <span class=\"span2\"><input type=\"text\" name=\"txtSpreader\" id=\"txtSpreader\" maxlength=\"10\" style=\"line-height:30px; height:30px; width:250px; border:  solid 1px #cfcfcf\"></span>\r\n");
      out.write("              <span class=\"span3\" id=\"txtSpreaderTip\">如无推荐人，责无需填写</span>\r\n");
      out.write("          </LI>\r\n");
      out.write("          <LI><span class=\"span1\"></span>\r\n");
      out.write("            <input type=\"checkbox\" id=\"chk_agree\" name=\"chk_agree\">\r\n");
      out.write("          我已阅读并同意<a href=\"#\"> 《都市棋牌游戏用户服务协议》</a><span id=\"id_agree\" class=\"id_agree\"></span></LI>\r\n");
      out.write("          <LI><span class=\"span1\"></span>\r\n");
      out.write("              <input type=\"hidden\" name=\"regmethod\" value=\"reg\"/>\r\n");
      out.write("            <input type=\"submit\" name=\"btnRegister\" id=\"btnRegister\" value=\"立即注册\">\r\n");
      out.write("          </LI>\r\n");
      out.write("        </ul>\r\n");
      out.write("              </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"remove\"></div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("<!--底部开始-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"foot\">\r\n");
      out.write("    <div class=\"box\">\r\n");
      out.write("        <div class=\"bottom_logo\">\r\n");
      out.write("            <img src=\"/images/bottom_logo.png\" alt=\"最好玩的棋牌平台\" width=\"158\" height=\"72\"/>\t\t</div>\r\n");
      out.write("        <div class=\"copyright\">\r\n");
      out.write("            健康游戏公告：抵制不良游戏 拒绝盗版游戏 注意自我保护 谨防受骗上当 适度游戏益脑 沉迷游戏伤身 合理安排时间 享受健康生活<br/>\r\n");
      out.write("            禁止任何利用本平台游戏进行赌博的行为，让我们共同净化游戏环境，一旦发现有违反用户协议的行为，我们将会冻结此玩家账号\r\n");
      out.write("            <br/>\r\n");
      out.write("            Copyright © 2015 Www.jiaqp.Com Asiasoft Inc.All Rights Reserved\r\n");
      out.write("            <a href=\"http://www.jiaqp.com\">渔人游戏中心</a> 版权所有 浙网文[2015]0342-112号 浙B2-20080029\t\t</div>\r\n");
      out.write("        <div class=\"remove\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--底部结束-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
