/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2016-01-12 13:58:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Com.ArticlePackages.Article_Pro;
import Com.ArticlePackages.SingleArticle;
import Com.SharePackages.checkStr;
import java.util.Iterator;

public final class sitehome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/include/left.jsp", Long.valueOf(1452482422099L));
    _jspx_dependants.put("/include/top.jsp", Long.valueOf(1452602257915L));
    _jspx_dependants.put("/include/foot.jsp", Long.valueOf(1443359240835L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      Com.SharePackages.Format_Date nowdate = null;
      nowdate = (Com.SharePackages.Format_Date) _jspx_page_context.getAttribute("nowdate", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (nowdate == null){
        nowdate = new Com.SharePackages.Format_Date();
        _jspx_page_context.setAttribute("nowdate", nowdate, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html xmlns=\"/www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("<title>渔人游戏－好玩的棋牌电玩游戏平台</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"渔人棋牌游戏,捕鱼,斗地主,梭哈,金花,水果机\"/>\r\n");
      out.write("<meta name=\"description\" content=\"信誉棋牌游戏,真正赚金的游戏-渔人。\"/>\r\n");
      out.write("<link type=\"image/gif\" rel=\"icon\" title=\"\" href=\"/images/animated_favicon1.gif\"/>\r\n");
      out.write("<link href=\"/style1/css.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jcarousellite_1.0.1.js\"></script>\r\n");
      out.write("</head> \r\n");
      out.write("<body> \r\n");
      out.write("\r\n");
      out.write("<!--头部开始-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"head\">\r\n");
      out.write("    <div class=\"topbar\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sideBar\">\r\n");
      out.write("            <div class=\"user\">\r\n");
      out.write("                <a href=\"/reg/gamelogin\" class=\"login\">账号登陆</a><a href=\"/reg/gamereg\">注册帐号</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"top_menu\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li class=\"curr\"><a href=\"/\">网站首页</a></li>\r\n");
      out.write("            <li><a href=\"/member\">用户中心</a></li>\r\n");
      out.write("            <li><a href=\"/download\">游戏下载</a></li>\r\n");
      out.write("            <li><a href=\"http://www.40zf.com/wxy/bank\">充值中心</a></li>\r\n");
      out.write("            <!--<li><a href=\"Popularize.html\">玩家推广</a></li>\r\n");
      out.write("            <li><a href=\"Roulette.html\">幸运抽奖</a></li>-->\r\n");
      out.write("            <li><a href=\"/news/list/cate/0\">棋牌资讯</a></li>\r\n");
      out.write("            <li><a href=\"/news/help/cate/1\">帮助中心</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!--头部结束-->\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("\t ");
      out.write("\r\n");
      out.write("<div class=\"common_left\">\r\n");
      out.write("    <!--左侧通用开始-->\r\n");
      out.write("    <div class=\"shortcut-box\">\r\n");
      out.write("        <div class=\"download\">\r\n");
      out.write("            <a href=\"/download\"><strong>游戏大厅下载</strong>\r\n");
      out.write("                <p>\r\n");
      out.write("                    版本号：15.09.01 软件大小：3.70M<br/>\r\n");
      out.write("                    发布时间：2015/09/01\r\n");
      out.write("                </p>\r\n");
      out.write("                <span>本游戏适合18岁以上的玩家</span></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"reg\">\r\n");
      out.write("            <a href=\"/reg/gamereg\">立即注册</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"recharge\">\r\n");
      out.write("            <a href=\"http://www.40zf.com/wxy/bank\" target=\"_blank\">账户充值</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container1 p20\">\r\n");
      out.write("        <div class=\"tt\">\r\n");
      out.write("            <span>常见问题</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"box\">\r\n");
      out.write("            <ul class=\"li1\">\r\n");
      out.write("                ");

                    Iterator QuaIt=SingleArticle.getInstance().getArticleDb().ArticleList("",
                            "4","*","article a",
                            "a.*","a.cateid=1 and a.islock=0",
                            "a.articleid","desc").iterator();
                    while (QuaIt.hasNext())
                    {
                        Article_Pro quapro=(Article_Pro)QuaIt.next();
                        if(quapro!=null)
                        {
                
      out.write("\r\n");
      out.write("                <li><a href=\"/news/article/id/");
      out.print(quapro.getCateid());
      out.write('/');
      out.print(quapro.getArticleid());
      out.write('"');
      out.write('>');
      out.print(quapro.getArticletitle());
      out.write("</a></li>\r\n");
      out.write("                ");

                        }
                        QuaIt.remove();
                    }
                
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"service p20\">\r\n");
      out.write("        <a target=\"_blank\" href=\"http://wpa.qq.com/msgrd?v=3&uin=10057357&site=qq&menu=yes\"><img border=\"0\" src=\"/images/qq.gif\" alt=\"点击这里给我发消息\" title=\"点击这里给我发消息\"></a>\r\n");
      out.write("        <div class=\"remove\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--左侧通用结束-->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"main_right\">\r\n");
      out.write("\t\t<div class=\"banner\">\r\n");
      out.write("\t\t\t<!--banner开始-->\r\n");
      out.write("\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("    var pic_width = 769; //图片宽度\r\n");
      out.write("    var pic_height = 262; //图片高度\r\n");
      out.write("    var button_pos = 4; //按扭位置 1左 2右 3上 4下\r\n");
      out.write("    var stop_time = 5000; //图片停留时间(1000为1秒钟)\r\n");
      out.write("    var show_text = 0; //是否显示文字标签 1显示 0不显示\r\n");
      out.write("    var txtcolor = \"000000\"; //文字色\r\n");
      out.write("    var bgcolor = \"DDDDDD\"; //背景色\r\n");
      out.write("    var imag = new Array();\r\n");
      out.write("    var link = new Array();\r\n");
      out.write("    var text = new Array();\r\n");
      out.write("    imag[1] = \"images/banner1.jpg\";\r\n");
      out.write("    link[1] = \"#\";\r\n");
      out.write("    text[1] = \"标题 1\";\r\n");
      out.write("    imag[2] = \"images/banner2.jpg\";\r\n");
      out.write("    link[2] = \"#\";\r\n");
      out.write("    text[2] = \"标题 2\";\r\n");
      out.write("    imag[3] = \"images/banner3.jpg\";\r\n");
      out.write("    link[3] = \"#\";\r\n");
      out.write("    text[3] = \"标题 3\";\r\n");
      out.write("    imag[4] = \"images/banner4.jpg\";\r\n");
      out.write("    link[4] = \"#\";\r\n");
      out.write("    text[4] = \"标题 4\";\r\n");
      out.write("    imag[5] = \"images/banner5.jpg\";\r\n");
      out.write("    link[5] = \"#\";\r\n");
      out.write("    text[5] = \"标题 5\";\r\n");
      out.write("    //可编辑内容结束\r\n");
      out.write("    var swf_height = show_text == 1 ? pic_height + 20 : pic_height;\r\n");
      out.write("    var pics = \"\", links = \"\", texts = \"\";\r\n");
      out.write("    for (var i = 1; i < imag.length; i++) {\r\n");
      out.write("        pics = pics + (\"|\" + imag[i]);\r\n");
      out.write("        links = links + (\"|\" + link[i]);\r\n");
      out.write("        texts = texts + (\"|\" + text[i]);\r\n");
      out.write("    }\r\n");
      out.write("    pics = pics.substring(1);\r\n");
      out.write("    links = links.substring(1);\r\n");
      out.write("    texts = texts.substring(1);\r\n");
      out.write("    document.write('<object classid=\"clsid:d27cdb6e-ae6d-11cf-96b8-444553540000\" codebase=\"/fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cabversion=6,0,0,0\" width=\"' + pic_width + '\" height=\"' + swf_height + '\">');\r\n");
      out.write("    document.write('<param name=\"movie\" value=\"images/focus.swf\">');\r\n");
      out.write("    document.write('<param name=\"quality\" value=\"high\"><param name=\"wmode\" value=\"opaque\">');\r\n");
      out.write("    document.write('<param name=\"FlashVars\" value=\"pics=' + pics + '&links=' + links + '&texts=' + texts + '&pic_width=' + pic_width + '&pic_height=' + pic_height + '&show_text=' + show_text + '&txtcolor=' + txtcolor + '&bgcolor=' + bgcolor + '&button_pos=' + button_pos + '&stop_time=' + stop_time + '\">');\r\n");
      out.write("    document.write('<embed src=\"images/focus.swf\" FlashVars=\"pics=' + pics + '&links=' + links + '&texts=' + texts + '&pic_width=' + pic_width + '&pic_height=' + pic_height + '&show_text=' + show_text + '&txtcolor=' + txtcolor + '&bgcolor=' + bgcolor + '&button_pos=' + button_pos + '&stop_time=' + stop_time + '\" quality=\"high\" width=\"' + pic_width + '\" height=\"' + swf_height + '\" allowScriptAccess=\"sameDomain\" type=\"application/x-shockwave-flash\" pluginspage=\"/www.macromedia.com/go/getflashplayer\" />');\r\n");
      out.write("    document.write('</object>');\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--banner结束-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"dynamic_box p20\">\r\n");
      out.write("\t\t\t<div class=\"news\">\r\n");
      out.write("\t\t\t\t<div class=\"tt\">\r\n");
      out.write("\t\t\t\t\t<a href=\"/news/list/cate/0\">more></a><span>渔人动态</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("                        ");

                            Iterator NewsIt=SingleArticle.getInstance().getArticleDb().ArticleList("",
                                    "8","*","article a",
                                    "a.*","a.cateid=0 and a.islock=0",
                                    "a.articleid","desc").iterator();
                            while (NewsIt.hasNext())
                            {
                                Article_Pro pro=(Article_Pro)NewsIt.next();
                                if(pro!=null)
                                {
                        
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><span>");
      out.print(nowdate.set_date(pro.getAddtime(),"yyyy-MM-dd"));
      out.write("</span> <a href='/news/article/id/");
      out.print(pro.getCateid());
      out.write('/');
      out.print(pro.getArticleid());
      out.write('\'');
      out.write('>');
      out.print(pro.getArticletitle());
      out.write("</a></li>\r\n");
      out.write("                        ");

                                }
                                NewsIt.remove();
                            }
                        
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"user_top\">\r\n");
      out.write("\t\t\t\t<div class=\"container1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tt\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"></a><span>财富排行榜</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t<dt class=\"n1\" runat=\"server\">1</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><span>34451.00</span>ID:aaa</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dt class=\"n2\" runat=\"server\">2</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><span>29392.00</span>ID:aaa</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dt class=\"n3\" runat=\"server\">3</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><span>24797.00</span>ID:aaa</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dt class=\"n4\" runat=\"server\">4</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><span>24683.00</span>ID:aaa</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dt class=\"n5\" runat=\"server\">5</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><span>22528.00</span>ID:aaa</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dt class=\"n6\" runat=\"server\">6</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><span>20467.00</span>ID:aaa</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dt class=\"n7\" runat=\"server\">7</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><span>16277.00</span>ID:aaa</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dt class=\"n8\" runat=\"server\">8</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><span>16132.00</span>ID:aaa</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dt class=\"n9\" runat=\"server\">9</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><span>14948.00</span>ID:aaa</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<dt class=\"n10\" runat=\"server\">10</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd><span>12608.00</span>ID:aaa</dd>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"remove\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"remove\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"remove\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"hot_game\">\r\n");
      out.write("\t\t<div class=\"tt\">\r\n");
      out.write("\t\t\t<a href=\"/download\">more></a><span>热门游戏</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"box\">\r\n");
      out.write("\t\t\t<div class=\"l\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"btn_focus_prev\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"dome1\">\r\n");
      out.write("\t\t\t\t<div class=\"game_list\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<!--热门游戏内容循环开始-->\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/download\" title=\"李逵劈鱼\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/2010.png\" width=\"100\" alt=\"李逵劈鱼\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/download\" style=\" color:#e76000;\">李逵劈鱼</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t李逵捕鱼是游戏中心精心推出的另一款捕鱼游戏，在保留了传统街机版本的界面...\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/download\" title=\"水果连线\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/655.jpg\" width=\"100\" alt=\"水果连线\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\" color:#e76000;\">水果连线</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t全球风靡的游戏，玩家控制启动停止，横竖斜面三个一样的图案即中奖...\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/download\" title=\"飞禽走兽\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/123.png\" width=\"100\" alt=\"飞禽走兽\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\" color:#e76000;\">飞禽走兽</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t飞禽走兽类似传统的水果机，是玩家是否压中开奖区域计算游戏输赢...\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/download\" title=\"斗地主\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/200.png\" width=\"100\" alt=\"斗地主\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\" color:#e76000;\">斗地主</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t斗地主是一款风靡全球的棋牌类游戏。是玩家两人合伙斗一人来计算游戏输赢...\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/download\" title=\"对战牛牛\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/27.png\" width=\"100\" alt=\"对战牛牛\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\" color:#e76000;\">对战牛牛</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t《对战牛牛》又名斗牛，是流行于我国浙南一带的牌类游戏玩法，由四人共同参与游戏...\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/download\" title=\"水果乐园\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/115.png\" width=\"100\" alt=\"水果乐园\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\" color:#e76000;\">水果乐园</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t超好玩的电玩游戏，西瓜，橘子，芒果，转到押注的图案即算中奖...\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/download\" title=\"二人梭哈\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/24.png\" width=\"100\" alt=\"二人梭哈\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\" color:#e76000;\">港式梭哈</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t梭哈游戏主要流行于我国广东、香港、澳门，由于游戏简单，激烈，既含有技巧也有...\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/download\" title=\"十三张\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/7.jpg\" width=\"100\" alt=\"十三张\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\" color:#e76000;\">十三张</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t是扑克游戏的一种。 有人说是俄罗斯扑克。该游戏适于 2、3 或 4 名玩家。 通常由四人一起玩...\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/download\" title=\"德州扑克\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/3.jpg\" width=\"100\" alt=\"德州扑克\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\" color:#e76000;\">德州扑克</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t德克萨斯扑克全称Texas Hold’em poker，中文简称德州扑克。是玩家对玩家的公共牌类游戏...\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/download\" title=\"扎金花\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/6.png\" width=\"100\" alt=\"金花\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\" color:#e76000;\">扎金花</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t又叫三张牌是在全国广泛流传的一种民间多人纸牌游戏、是玩家对玩家的公共牌类游戏...\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"pic\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/download\" title=\"二人麻将\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/images/358.png\" width=\"100\" alt=\"二人麻将\" height=\"100\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" style=\" color:#e76000;\">二人麻将</a>\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t二人麻将是最受欢迎的二人麻将对战游戏,规则简单,画面精美,有趣好玩,娱乐性强...\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<!--热门游戏内容循环结束-->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("               $(function () {\r\n");
      out.write("                   var clearTimer = null;\r\n");
      out.write("                   var SleepTime = 2500;   //停留时长，单位毫秒\r\n");
      out.write("                   $(\".game_list\").jCarouselLite({\r\n");
      out.write("                       btnNext: \"#btn_focus_next\",\r\n");
      out.write("                       btnPrev: \"#btn_focus_prev\",\r\n");
      out.write("                       visible: 3,\r\n");
      out.write("                       scroll: 1,\r\n");
      out.write("                       speed: 500, //滚动速度，单位毫秒\r\n");
      out.write("                       auto: 2500,\r\n");
      out.write("                       mouseOver: true\r\n");
      out.write("                   });\r\n");
      out.write("               });\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"r\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" id=\"btn_focus_next\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--底部开始-->\r\n");
      out.write("\r\n");
      out.write("<div id=\"foot\">\r\n");
      out.write("    <div class=\"box\">\r\n");
      out.write("        <div class=\"bottom_logo\">\r\n");
      out.write("            <img src=\"/images/bottom_logo.png\" alt=\"最好玩的棋牌平台\" width=\"158\" height=\"72\"/>\t\t</div>\r\n");
      out.write("        <div class=\"copyright\">\r\n");
      out.write("            健康游戏公告：抵制不良游戏 拒绝盗版游戏 注意自我保护 谨防受骗上当 适度游戏益脑 沉迷游戏伤身 合理安排时间 享受健康生活<br/>\r\n");
      out.write("            禁止任何利用本平台游戏进行赌博的行为，让我们共同净化游戏环境，一旦发现有违反用户协议的行为，我们将会冻结此玩家账号\r\n");
      out.write("            <br/>\r\n");
      out.write("            Copyright © 2015 Www.jiaqp.Com Asiasoft Inc.All Rights Reserved\r\n");
      out.write("            <a href=\"http://www.jiaqp.com\">渔人游戏中心</a> 版权所有 浙网文[2015]0342-112号 浙B2-20080029\t\t</div>\r\n");
      out.write("        <div class=\"remove\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--底部结束-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
