/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-09-28 13:45:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Ds_005fAdmin.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Com.SysSetPackages.UserSetPackages.ProxyUserPackages.UserPurview;
import Com.SysSetPackages.UserSetPackages.ProxyUserPackages.ProxyUserPurview;
import Com.SharePackages.checkStr;
import Com.SharePackages.Field_Str;

public final class memberlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Ds_Admin/include/userproxy.jsp", Long.valueOf(1417490842773L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      Com.SharePackages.Str_code_switch tostr = null;
      tostr = (Com.SharePackages.Str_code_switch) _jspx_page_context.getAttribute("tostr", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (tostr == null){
        tostr = new Com.SharePackages.Str_code_switch();
        _jspx_page_context.setAttribute("tostr", tostr, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    String bid = tostr.to_utf_8 (request.getParameter ("bid"));
    String sid = tostr.to_utf_8 (request.getParameter ("sid"));
    UserPurview UserProxy = new ProxyUserPurview();
    String UserProxyStr = UserProxy.UserProxy (request);
    if (checkStr.isNull (UserProxyStr))
    {
        out.print("抱歉，您无权操作此模块");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>注册会员管理</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/web.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/");
      out.print(checkStr.Parame(request,2));
      out.write("/easyui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/icon.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/validata.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        //修改资料\r\n");
      out.write("        function EditMember() {\r\n");
      out.write("            var selected = $('#UserList').datagrid('getSelections');\r\n");
      out.write("            if (selected) {\r\n");
      out.write("                var ids = [];\r\n");
      out.write("                for (var i = 0; i < selected.length; i++)\r\n");
      out.write("                {\r\n");
      out.write("                    ids.push(selected[i].code);\r\n");
      out.write("                }\r\n");
      out.write("                if (ids.length <= 0)\r\n");
      out.write("                {\r\n");
      out.write("                    $.messager.alert('系统提示', '抱歉，请先选择一行数据', 'warning');\r\n");
      out.write("                }\r\n");
      out.write("                else if (ids.length > 1)\r\n");
      out.write("                {\r\n");
      out.write("                    $.messager.alert('系统提示', '抱歉，请不要选择多行数据', 'warning');\r\n");
      out.write("                }\r\n");
      out.write("                else\r\n");
      out.write("                {\r\n");
      out.write("                    OpenDetail('资料修改', 'memberedit.jsp?memberid=' + ids.join(\",\") + '&bid=");
      out.print(bid);
      out.write("&sid=");
      out.print(sid);
      out.write("', 580, 340);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                $.messager.alert('系统提示', '请先选择一行数据', 'info');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        //设置密码\r\n");
      out.write("        function EditPwd() {\r\n");
      out.write("            var selected = $('#UserList').datagrid('getSelections');\r\n");
      out.write("            if (selected) {\r\n");
      out.write("                var ids = [];\r\n");
      out.write("                for (var i = 0; i < selected.length; i++)\r\n");
      out.write("                {\r\n");
      out.write("                    ids.push(selected[i].code);\r\n");
      out.write("                }\r\n");
      out.write("                if (ids.length <= 0)\r\n");
      out.write("                {\r\n");
      out.write("                    $.messager.alert('系统提示', '抱歉，请先选择一行数据', 'warning');\r\n");
      out.write("                }\r\n");
      out.write("                else if (ids.length > 1)\r\n");
      out.write("                {\r\n");
      out.write("                    $.messager.alert('系统提示', '抱歉，请不要选择多行数据', 'warning');\r\n");
      out.write("                }\r\n");
      out.write("                else\r\n");
      out.write("                {\r\n");
      out.write("                    OpenDetail('密码重置', 'memberpwdedit.jsp?memberid=' + ids.join(\",\") + '&bid=");
      out.print(bid);
      out.write("&sid=");
      out.print(sid);
      out.write("', 500, 400);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                $.messager.alert('系统提示', '请先选择一行数据', 'info');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        //修改真实姓名\r\n");
      out.write("        function EditRealName() {\r\n");
      out.write("            var selected = $('#UserList').datagrid('getSelections');\r\n");
      out.write("            if (selected) {\r\n");
      out.write("                var ids = [];\r\n");
      out.write("                for (var i = 0; i < selected.length; i++)\r\n");
      out.write("                {\r\n");
      out.write("                    ids.push(selected[i].code);\r\n");
      out.write("                }\r\n");
      out.write("                if (ids.length <= 0)\r\n");
      out.write("                {\r\n");
      out.write("                    $.messager.alert('系统提示', '抱歉，请先选择一行数据', 'warning');\r\n");
      out.write("                }\r\n");
      out.write("                else if (ids.length > 1)\r\n");
      out.write("                {\r\n");
      out.write("                    $.messager.alert('系统提示', '抱歉，请不要选择多行数据', 'warning');\r\n");
      out.write("                }\r\n");
      out.write("                else\r\n");
      out.write("                {\r\n");
      out.write("                    OpenDetail('资料真实姓名', 'membernameedit.jsp?memberid=' + ids.join(\",\") + '&bid=");
      out.print(bid);
      out.write("&sid=");
      out.print(sid);
      out.write("', 580, 340);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                $.messager.alert('系统提示', '请先选择一行数据', 'info');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        //设置经纪人\r\n");
      out.write("        function EditBokey() {\r\n");
      out.write("            var selected = $('#UserList').datagrid('getSelections');\r\n");
      out.write("            if (selected.length <= 0)\r\n");
      out.write("            {\r\n");
      out.write("                $.messager.alert('系统提示', '抱歉，请至少选择一行数据', 'warning');\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                var ids = [];\r\n");
      out.write("                for (var i = 0; i < selected.length; i++)\r\n");
      out.write("                {\r\n");
      out.write("                    ids.push(selected[i].code);\r\n");
      out.write("                }\r\n");
      out.write("                OpenDetail('经纪人设置', 'borkeyset.jsp?memberid=' + ids.join(\",\") + '&bid=");
      out.print(bid);
      out.write("&sid=");
      out.print(sid);
      out.write("', 500, 400);\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        //设置贵宾用户\r\n");
      out.write("        function EditVip() {\r\n");
      out.write("            var selected = $('#UserList').datagrid('getSelections');\r\n");
      out.write("            if (selected.length <= 0)\r\n");
      out.write("            {\r\n");
      out.write("                $.messager.alert('系统提示', '抱歉，请至少选择一行数据', 'warning');\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                var ids = [];\r\n");
      out.write("                for (var i = 0; i < selected.length; i++)\r\n");
      out.write("                {\r\n");
      out.write("                    ids.push(selected[i].code);\r\n");
      out.write("                }\r\n");
      out.write("                OpenDetail('贵宾用户设置', 'vipset.jsp?memberid=' + ids.join(\",\") + '&bid=");
      out.print(bid);
      out.write("&sid=");
      out.print(sid);
      out.write("', 500, 400);\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        //设置超级用户\r\n");
      out.write("        function EditSup() {\r\n");
      out.write("            var selected = $('#UserList').datagrid('getSelections');\r\n");
      out.write("            if (selected.length <= 0)\r\n");
      out.write("            {\r\n");
      out.write("                $.messager.alert('系统提示', '抱歉，请至少选择一行数据', 'warning');\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                var ids = [];\r\n");
      out.write("                for (var i = 0; i < selected.length; i++)\r\n");
      out.write("                {\r\n");
      out.write("                    ids.push(selected[i].code);\r\n");
      out.write("                }\r\n");
      out.write("                OpenDetail('超级用户设置', 'supset.jsp?memberid=' + ids.join(\",\") + '&bid=");
      out.print(bid);
      out.write("&sid=");
      out.print(sid);
      out.write("', 500, 400);\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        $(function () {\r\n");
      out.write("            //刷新按钮\r\n");
      out.write("            $('#reload').bind('click', function () {\r\n");
      out.write("                $('#UserList').datagrid('load');\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            $('#UserList').datagrid({\r\n");
      out.write("                title: '会员管理',\r\n");
      out.write("                iconCls: 'icon-save',//图标\r\n");
      out.write("                nowrap: true,\r\n");
      out.write("                autoRowHeight: true,\r\n");
      out.write("                border: false,\r\n");
      out.write("                striped: true,\r\n");
      out.write("                collapsible: true,//是否可折叠的\r\n");
      out.write("                loadMsg: 'loading...',\r\n");
      out.write("                pagination: true,\r\n");
      out.write("                rownumbers: false,\r\n");
      out.write("                singleSelect: false,\r\n");
      out.write("                fit: true,\r\n");
      out.write("                pageSize: 30,//每页显示的记录条数，默认为10\r\n");
      out.write("                toolbar: '#toolbar',\r\n");
      out.write("                onBeforeLoad: function (data) {\r\n");
      out.write("                },//数据加载前\r\n");
      out.write("                onLoadError: function (data) {\r\n");
      out.write("                    $.messager.alert('系统提示', '抱歉，数据加载出错', 'info');\r\n");
      out.write("                },//数据加载出错\r\n");
      out.write("                onLoadSuccess: function (data) {\r\n");
      out.write("                    if (eval(data).total <= 0) {\r\n");
      out.write("                        $('#UserList').datagrid('deleteRow', 0);\r\n");
      out.write("                    }\r\n");
      out.write("                    //$.mask().hide();\r\n");
      out.write("                },//数据加载完闭\r\n");
      out.write("                url: '/Action/MemberWriter.do?membermark=pagelist',\r\n");
      out.write("                idField: 'code',\r\n");
      out.write("                frozenColumns: [\r\n");
      out.write("                    [\r\n");
      out.write("                        {field: 'code', checkbox: true}\r\n");
      out.write("                    ]\r\n");
      out.write("                ],\r\n");
      out.write("                columns: [\r\n");
      out.write("                    [\r\n");
      out.write("                        {title: '会员ID', field: 'memberid', width: 60, align: 'center'},\r\n");
      out.write("                        {title: '登录帐号', field: 'loginname', width: 140, align: 'center'},\r\n");
      out.write("                        {title: '称昵', field: 'nick', width: 80, align: 'center'},\r\n");
      out.write("                        {title: '推荐人ID', field: 'tjmemberid', width: 80, align: 'center',\r\n");
      out.write("                            formatter:function(value,rec){\r\n");
      out.write("                                if(value==0)\r\n");
      out.write("                                    return '未有推荐人';\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        {title: '真实姓名', field: 'realname', width: 80, align: 'center'},\r\n");
      out.write("                        {title: '姓别', field: 'sex', width: 50, align: 'center',\r\n");
      out.write("                            formatter:function(value,rec){\r\n");
      out.write("                                if(value==0)\r\n");
      out.write("                                    return '男';\r\n");
      out.write("                                else if(value==1)\r\n");
      out.write("                                    return '女';\r\n");
      out.write("                                else\r\n");
      out.write("                                    return '未知';\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        {title: '生日', field: 'birdate', width: 80, align: 'center'},\r\n");
      out.write("                        {title: '联系手机', field: 'tel', width: 100, align: 'center'},\r\n");
      out.write("                        {title: 'QQ', field: 'qq', width: 80, align: 'center'},\r\n");
      out.write("                        {title: 'E_mail', field: 'email', width: 150, align: 'center'},\r\n");
      out.write("                        {title: '身份证号', field: 'idnum', width: 200, align: 'center'},\r\n");
      out.write("                        {title: '是否有头像', field: 'headimg', width: 80, align: 'center',\r\n");
      out.write("                            formatter:function(value,rec){\r\n");
      out.write("                                if(value==\"\")\r\n");
      out.write("                                    return '未有头像';\r\n");
      out.write("                                else\r\n");
      out.write("                                    return '有头像';\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        {title: '状态', field: 'status', width: 40, align: 'center',\r\n");
      out.write("                            styler:function(value,row,index){\r\n");
      out.write("                                if(value=='1' || value=='2')\r\n");
      out.write("                                {\r\n");
      out.write("                                    return 'background-color:#ffee00;color:red;';\r\n");
      out.write("                                }\r\n");
      out.write("                            },\r\n");
      out.write("                            formatter:function(value,rec){\r\n");
      out.write("                                if(value==0)\r\n");
      out.write("                                    return '正常';\r\n");
      out.write("                                else if(value==1)\r\n");
      out.write("                                    return '锁定';\r\n");
      out.write("                                else if(value==2)\r\n");
      out.write("                                    return '休眠';\r\n");
      out.write("                                else\r\n");
      out.write("                                    return '未知';\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        {title: '备注', field: 'note', width: 400, align: 'center'},\r\n");
      out.write("                        {title: '注册IP', field: 'regip', width: 100, align: 'center'},\r\n");
      out.write("                        {title: '注册时间', field: 'regtime', width: 120, align: 'center'}\r\n");
      out.write("                    ]\r\n");
      out.write("                ],\r\n");
      out.write("                rowStyler: function (index, row) {\r\n");
      out.write("                    return 'height:28px;';\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            $('#qsubmit').bind(\"click\", function () {\r\n");
      out.write("                $('#UserList').datagrid('load', {\r\n");
      out.write("                    membermark: 'pagelist',\r\n");
      out.write("                    memberid:$('#memberid').val(),\r\n");
      out.write("                    logemail: $('#logemail').val(),\r\n");
      out.write("                    name: $('#name').val(),\r\n");
      out.write("                    phone: $('#phone').val(),\r\n");
      out.write("                    tel: $(\"#tel\").val(),\r\n");
      out.write("                    qq: $(\"#qq\").val(),\r\n");
      out.write("                    islock: $('#islock').combobox('getValue'),\r\n");
      out.write("                    isvip: $('#isvip').combobox('getValue'),\r\n");
      out.write("                    issup: $('#issup').combobox('getValue'),\r\n");
      out.write("                    borkeyid: $('#borkeyid').combobox('getValue'),\r\n");
      out.write("                    isactivation: $('#isactivation').combobox('getValue'),\r\n");
      out.write("                    reg_start_time: $(\"#reg_start_time\").datebox(\"getValue\"),\r\n");
      out.write("                    reg_end_time: $(\"#reg_end_time\").datebox(\"getValue\"),\r\n");
      out.write("                    login_start_time: $(\"#login_start_time\").datebox(\"getValue\"),\r\n");
      out.write("                    login_end_time: $(\"#login_end_time\").datebox(\"getValue\")\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("            //输入电子邮件时,按键释放时触发\r\n");
      out.write("            $(\"#memberid,#logemail,#name,#photo,#tel\").keyup(function () {\r\n");
      out.write("                $('#UserList').datagrid('load', {\r\n");
      out.write("                    membermark: 'pagelist',\r\n");
      out.write("                    memberid:$('#memberid').val(),\r\n");
      out.write("                    logname: $('#logname').val(),\r\n");
      out.write("                    name: $('#name').val(),\r\n");
      out.write("                    tel: $(\"#tel\").val(),\r\n");
      out.write("                    qq: $(\"#qq\").val(),\r\n");
      out.write("                    status: $('#status').combobox('getValue'),\r\n");
      out.write("                    reg_start_time: $(\"#reg_start_time\").datebox(\"getValue\"),\r\n");
      out.write("                    reg_end_time: $(\"#reg_end_time\").datebox(\"getValue\")\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function DelUser() {\r\n");
      out.write("            var selected = $('#UserList').datagrid('getSelections');\r\n");
      out.write("            if (selected.length <= 0)\r\n");
      out.write("            {\r\n");
      out.write("                $.messager.alert('系统提示', '抱歉，请先选择一行数据', 'warning');\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                $.messager.confirm('系统提示', '<span style=\"line-height: 20px;\">您确定要删除您所选的注册会员吗?<br>删除之后相关数据将一同删除！</span>', function (r) {\r\n");
      out.write("                    if (r)\r\n");
      out.write("                    {\r\n");
      out.write("                        var ids = [];\r\n");
      out.write("                        for (var i = 0; i < selected.length; i++)\r\n");
      out.write("                        {\r\n");
      out.write("                            ids.push(selected[i].code);\r\n");
      out.write("                        }\r\n");
      out.write("                        $.post('/Action/Member.do?memberid=' + ids.join(\",\") + '&bid=");
      out.print(bid);
      out.write("&sid=");
      out.print(sid);
      out.write("&membermethod=del', function (msg) {\r\n");
      out.write("                            var jsondata = eval('(' + msg + ')');\r\n");
      out.write("                            if (jsondata.err == \"\")//表示没有出错\r\n");
      out.write("                            {\r\n");
      out.write("                                $(\"#UserList\").datagrid('load');\r\n");
      out.write("                            }\r\n");
      out.write("                            else {\r\n");
      out.write("                                $.messager.alert('系统提示', jsondata.err, 'error');\r\n");
      out.write("                            }\r\n");
      out.write("                            //close();\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        function DelHead()\r\n");
      out.write("        {\r\n");
      out.write("            var selected = $('#UserList').datagrid('getSelections');\r\n");
      out.write("            if (selected.length <= 0)\r\n");
      out.write("            {\r\n");
      out.write("                $.messager.alert('系统提示', '抱歉，请先选择一行数据', 'warning');\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                $.messager.confirm('系统提示', '<span style=\"line-height: 20px;\">您确定要删除您所选的注册会员的头像吗?<br>删除之后相将不可恢复！</span>', function (r) {\r\n");
      out.write("                    if (r)\r\n");
      out.write("                    {\r\n");
      out.write("                        var ids = [];\r\n");
      out.write("                        for (var i = 0; i < selected.length; i++)\r\n");
      out.write("                        {\r\n");
      out.write("                            ids.push(selected[i].code);\r\n");
      out.write("                        }\r\n");
      out.write("                        $.post('/Action/SysMember.do?userid=' + ids.join(\",\") + '&bid=");
      out.print(bid);
      out.write("&sid=");
      out.print(sid);
      out.write("&usermethod=del_head', function (msg) {\r\n");
      out.write("                            var jsondata = eval('(' + msg + ')');\r\n");
      out.write("                            if (jsondata.err == \"\")//表示没有出错\r\n");
      out.write("                            {\r\n");
      out.write("                                $(\"#UserList\").datagrid('load');\r\n");
      out.write("                            }\r\n");
      out.write("                            else {\r\n");
      out.write("                                $.messager.alert('系统提示', jsondata.err, 'error');\r\n");
      out.write("                            }\r\n");
      out.write("                            //close();\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("<div region=\"east\" title=\"查询条件\" iconCls=\"icon-search\"\r\n");
      out.write("     style=\"width:180px;overflow:auto;\" split=\"true\" border=\"false\">\r\n");
      out.write("    <form id=\"form\" method=\"post\">\r\n");
      out.write("        <table class=\"table-edit\" width=\"100%\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"line-height: 14px;\">\r\n");
      out.write("                    <b>会员ID</b>\r\n");
      out.write("                    <input type=\"text\" id=\"memberid\" name=\"memberid\"\r\n");
      out.write("                           class=\"easyui-numberbox\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"line-height: 14px;\">\r\n");
      out.write("                    <b>登录名</b>\r\n");
      out.write("                    <input type=\"text\" id=\"logname\" name=\"logname\" class=\"easyui-validatebox\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"line-height: 14px;\">\r\n");
      out.write("                    <b>真实姓名</b>\r\n");
      out.write("                    <input type=\"text\" id=\"name\" name=\"name\" class=\"easyui-validatebox\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"line-height: 14px;\">\r\n");
      out.write("                    <b>联系手机</b>\r\n");
      out.write("                    <input type=\"text\" id=\"tel\" name=\"tel\"\r\n");
      out.write("                           class=\"easyui-numberbox\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"line-height: 14px;\">\r\n");
      out.write("                    <b>联系QQ</b>\r\n");
      out.write("                    <input type=\"text\" id=\"qq\" name=\"qq\"\r\n");
      out.write("                           class=\"easyui-numberbox\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"line-height: 16px;\">\r\n");
      out.write("                    <b>会员状态</b>\r\n");
      out.write("                    <select id=\"status\" class=\"easyui-combobox\" name=\"status\" style=\"width:150px;*width: 155px;\"\r\n");
      out.write("                            data-options=\"required:false,editable:false,panelHeight:60\">\r\n");
      out.write("                        <option value=\"\">==全部==</option>\r\n");
      out.write("                        <option value=\"0\">正常</option>\r\n");
      out.write("                        <option value=\"1\">锁定</option>\r\n");
      out.write("                        <option value=\"2\">休眠</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td style=\"line-height: 20px;\">\r\n");
      out.write("                    <b>注册时间</b><span class=\"operator\"><a name=\"reg-time-opt\" opt=\"date\"></a></span><br>\r\n");
      out.write("                    大于<input type=\"text\" id=\"reg_start_time\" name=\"reg_start_time\" class=\"easyui-datebox\"\r\n");
      out.write("                             style=\"width: 126px;*width:130px;\"/>\r\n");
      out.write("\r\n");
      out.write("                    <div style=\"font-size: 1px; height: 5px;\"></div>\r\n");
      out.write("                    小于<input type=\"text\" id=\"reg_end_time\" name=\"reg_end_time\" class=\"easyui-datebox\"\r\n");
      out.write("                             style=\"width: 126px;*width:130px;\"/>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"datagrid-toolbar\" align=\"left\">\r\n");
      out.write("            <a id=\"qsubmit\" class=\"easyui-linkbutton\" plain=\"true\" icon=\"icon-search\">查询</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<div region=\"center\" style=\"overflow:hidden;\" border=\"false\">\r\n");
      out.write("    <div class=\"datagrid-toolbar\" id=\"toolbar\">\r\n");
      out.write("        <a id=\"reload\" href=\"javascript:void('');\" class=\"easyui-linkbutton\" plain=\"true\"\r\n");
      out.write("           data-options=\"iconCls:'icon-reload'\">刷新</a>\r\n");
      out.write("        ");

            if (! checkStr.isNull (UserProxy.UserOptProxy (request, UserProxyStr, "0")))
            {
        
      out.write("\r\n");
      out.write("        <a id=\"add\" href=\"javascript:void('');\" onclick=\"DelUser();\" class=\"easyui-linkbutton\" plain=\"true\"\r\n");
      out.write("           data-options=\"iconCls:'icon-cancel'\">删除</a>\r\n");
      out.write("        ");

            }
            if (! checkStr.isNull (UserProxy.UserOptProxy (request, UserProxyStr, "1")))
            {
        
      out.write("\r\n");
      out.write("        <a id=\"delete\" href=\"javascript:void('');\" onclick=\"EditMember();\" class=\"easyui-linkbutton\" plain=\"true\"\r\n");
      out.write("           icon=\"icon-edit\">资料修改</a>\r\n");
      out.write("        ");

            }
            if (! checkStr.isNull (UserProxy.UserOptProxy (request, UserProxyStr, "2"))) {
        
      out.write("\r\n");
      out.write("        <a id=\"delete\" href=\"javascript:void('');\" onclick=\"EditPwd();\" class=\"easyui-linkbutton\" plain=\"true\"\r\n");
      out.write("           icon=\"icon-pwd\">密码重置</a>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <table id=\"UserList\"></table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
