/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-09-28 13:44:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Ds_005fAdmin.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Com.SysSetPackages.UserSetPackages.ProxyUserPackages.UserPurview;
import Com.SysSetPackages.UserSetPackages.ProxyUserPackages.ProxyUserPurview;
import Com.SharePackages.checkStr;
import Com.SharePackages.Field_Str;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      Com.SharePackages.Str_code_switch tostr = null;
      tostr = (Com.SharePackages.Str_code_switch) _jspx_page_context.getAttribute("tostr", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (tostr == null){
        tostr = new Com.SharePackages.Str_code_switch();
        _jspx_page_context.setAttribute("tostr", tostr, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    UserPurview UserProxy = new ProxyUserPurview ();
    String UserStr = UserProxy.UserSelect (request);
    if (checkStr.isNull (UserStr) || ! UserStr.contains (",")) {
        out.print ("抱歉，请重新登录之后在操作");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <title>");
      out.print(checkStr.Parame(request,1));
      out.write("</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/web.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/");
      out.print(checkStr.Parame(request,2));
      out.write("/easyui.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/icon.css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/jqueryUtil.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src='/Ds_Admin/js/outlook2.js'></script>\r\n");
      out.write("    <script type=\"text/javascript\" src='/Ds_Admin/js/validata.js'></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function EditMyPwd() {\r\n");
      out.write("            OpenDetail('修改密码', '../myinfo/mypwdedit.jsp', 580, 350);\r\n");
      out.write("        }\r\n");
      out.write("        function EditMyInfo() {\r\n");
      out.write("            OpenDetail('修改资料', '../myinfo/myinfoedit.jsp', 780, 500);\r\n");
      out.write("        }\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $('#loginOut').click(function () {\r\n");
      out.write("                $.messager.confirm('系统提示', '您确定要退出本次登录吗?', function (r) {\r\n");
      out.write("                    if (r) {\r\n");
      out.write("                        location.href = '/Action/LoginOut.do';\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            })\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\" style=\"overflow-y: hidden\" scroll=\"no\">\r\n");
      out.write("<noscript>\r\n");
      out.write("    <div style=\" position:absolute; z-index:100000; height:2046px;top:0;left:0; width:100%; background:white; text-align:center;\">\r\n");
      out.write("        <img src=\"/Ds_Admin/images/noscript.gif\" alt='抱歉，请开启脚本支持！'/>\r\n");
      out.write("    </div>\r\n");
      out.write("</noscript>\r\n");
      out.write("<div region=\"north\" split=\"true\" border=\"false\"\r\n");
      out.write("     style=\"overflow: hidden; height: 30px;background: url(/Ds_Admin/images/layout-browser-hd-bg.gif) #7f99be repeat-x center 50%;line-height: 20px;color: #fff; font-family: Verdana, '微软雅黑','黑体',serif;\">\r\n");
      out.write("    <span style=\"float:right; padding-right:20px;\" class=\"head\">欢迎您 ");
      out.print(UserStr.split (",")[1]);
      out.write(" <a\r\n");
      out.write("            href=\"javascript:void('');\" id=\"editpass\" class=\"top\" onclick=\"EditMyPwd();\">修改密码</a> <a href=\"javascript:void('');\"\r\n");
      out.write("                                                                              onclick=\"EditMyInfo();\"\r\n");
      out.write("                                                                              class=\"top\" id=\"editinfo\">修改基本资料</a> <a\r\n");
      out.write("            href=\"javascript:void('');\" class=\"top\" id=\"loginOut\">安全退出</a></span>\r\n");
      out.write("    <span style=\"padding-left:10px; font-size: 14px; \"><img src=\"/Ds_Admin/images/blocks.gif\" width=\"20\" height=\"20\"\r\n");
      out.write("                                                            align=\"absmiddle\"/> 欢迎您进入");
      out.print(checkStr.Parame(request,1));
      out.write("</span>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div region=\"west\" hide=\"true\" border=\"true\" split=\"true\" title=\"导航菜单\" style=\"width:180px;\" id=\"west\">\r\n");
      out.write("    <div class=\"easyui-accordion\" data-options=\"fit:true,border:false\">\r\n");
      out.write("        ");

            for (int i = 0; i < UserStr.split (",")[4].split ("&").length; i++) {
        
      out.write("\r\n");
      out.write("        <div border=\"false\" title=\"");
      out.print(Field_Str.Menu_Type[Integer.parseInt(UserStr.split(",")[4].split("&")[i])]);
      out.write("\"\r\n");
      out.write("             style=\"padding:10px;overflow:auto;\">\r\n");
      out.write("            <ul class=\"easyui-tree\">\r\n");
      out.write("                ");

                    //for (int ii = 0; ii < UserStr.split (",")[5].split ("\\|")[Integer.parseInt (UserStr.split (",")[4].split ("&")[i])].split ("&").length; ii++) {
                    for (int ii = 0; ii < UserStr.split (",")[5].split ("\\|")[i].split ("&").length; ii++) {
                
      out.write("\r\n");
      out.write("                <li>\r\n");
      out.write("                    <span><a href=\"javascript:void('');\"\r\n");
      out.write("                             onclick=\"addTab('");
      out.print(Field_Str.Menu_Small_Type[Integer.parseInt(UserStr.split(",")[4].split("&")[i])][Integer.parseInt(UserStr.split(",")[5].split("\\|")[i].split("&")[ii])]);
      out.write("','../");
      out.print(Field_Str.Menu_Type_Link[Integer.parseInt(UserStr.split(",")[4].split("&")[i])][Integer.parseInt(UserStr.split(",")[5].split("\\|")[i].split("&")[ii])]+"bid="+UserStr.split(",")[4].split("&")[i]+"&sid="+UserStr.split(",")[5].split("\\|")[i].split("&")[ii]);
      out.write("');\">");
      out.print(Field_Str.Menu_Small_Type[Integer.parseInt (UserStr.split (",")[4].split ("&")[i])][Integer.parseInt (UserStr.split (",")[5].split ("\\|")[i].split ("&")[ii])]);
      out.write("\r\n");
      out.write("                    </a></span>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"mainPanle\" region=\"center\" style=\"background: #eee; overflow-y:hidden\">\r\n");
      out.write("    <div id=\"tabs\" class=\"easyui-tabs\" fit=\"true\" border=\"false\">\r\n");
      out.write("        <div title=\"欢迎使用\" style=\"padding:20px;overflow:hidden; color:red; \">\r\n");
      out.write("            <h1 style=\"font-size:24px;\">* 欢迎您进入");
      out.print(checkStr.Parame(request,1));
      out.write("</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--修改密码窗口-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"mm\" class=\"easyui-menu\" style=\"width:150px;\">\r\n");
      out.write("    <div id=\"mm-tabupdate\">刷新</div>\r\n");
      out.write("    <div class=\"menu-sep\"></div>\r\n");
      out.write("    <div id=\"mm-tabclose\">关闭</div>\r\n");
      out.write("    <div id=\"mm-tabcloseall\">全部关闭</div>\r\n");
      out.write("    <div id=\"mm-tabcloseother\">除此之外全部关闭</div>\r\n");
      out.write("    <div class=\"menu-sep\"></div>\r\n");
      out.write("    <div id=\"mm-tabcloseright\">当前页右侧全部关闭</div>\r\n");
      out.write("    <div id=\"mm-tabcloseleft\">当前页左侧全部关闭</div>\r\n");
      out.write("    <div class=\"menu-sep\"></div>\r\n");
      out.write("    <div id=\"mm-exit\">退出</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
