/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-09-28 13:44:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Ds_005fAdmin.sysset.parame;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Com.SysSetPackages.UserSetPackages.ProxyUserPackages.UserPurview;
import Com.SysSetPackages.UserSetPackages.ProxyUserPackages.ProxyUserPurview;
import Com.SharePackages.checkStr;

public final class paramelist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Ds_Admin/include/userproxy.jsp", Long.valueOf(1417490842773L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      Com.SharePackages.Str_code_switch tostr = null;
      tostr = (Com.SharePackages.Str_code_switch) _jspx_page_context.getAttribute("tostr", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (tostr == null){
        tostr = new Com.SharePackages.Str_code_switch();
        _jspx_page_context.setAttribute("tostr", tostr, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    String bid = tostr.to_utf_8 (request.getParameter ("bid"));
    String sid = tostr.to_utf_8 (request.getParameter ("sid"));
    UserPurview UserProxy = new ProxyUserPurview();
    String UserProxyStr = UserProxy.UserProxy (request);
    if (checkStr.isNull (UserProxyStr))
    {
        out.print("抱歉，您无权操作此模块");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <title>参数列表</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/Ds_Admin/css/web.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/");
      out.print(checkStr.Parame(request,2));
      out.write("/easyui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/icon.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/validata.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function AddParame()\r\n");
      out.write("        {\r\n");
      out.write("            OpenDetail('参数增加','parameadd.jsp?bid=");
      out.print(bid);
      out.write("&sid=");
      out.print(sid);
      out.write("',600,350);\r\n");
      out.write("        }\r\n");
      out.write("        function EditParame()\r\n");
      out.write("        {\r\n");
      out.write("            var selected = $('#ParameList').datagrid('getSelected');\r\n");
      out.write("            if (selected){\r\n");
      out.write("                OpenDetail('参数修改','parameedit.jsp?parameid='+selected.parameid+'&bid=");
      out.print(bid);
      out.write("&sid=");
      out.print(sid);
      out.write("',600,350);\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                $.messager.alert('系统提示', '请先选择一行数据', 'info');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        $(function() {\r\n");
      out.write("            //刷新按钮\r\n");
      out.write("            $('#reload').bind('click', function () {\r\n");
      out.write("                $('#ParameList').datagrid('load');\r\n");
      out.write("            });\r\n");
      out.write("            $('#ParameList').datagrid({\r\n");
      out.write("                title:'参数列表',\r\n");
      out.write("                iconCls:'icon-save',//图标\r\n");
      out.write("                nowrap: true,\r\n");
      out.write("                autoRowHeight: false,\r\n");
      out.write("                border:false,\r\n");
      out.write("                striped: true,\r\n");
      out.write("                collapsible:true,//是否可折叠的\r\n");
      out.write("                loadMsg:'loading...',\r\n");
      out.write("                pagination:false,\r\n");
      out.write("                rownumbers:false,\r\n");
      out.write("                singleSelect:true,\r\n");
      out.write("                fit:true,\r\n");
      out.write("                toolbar:'#parame_toolbar',\r\n");
      out.write("                onBeforeLoad:function(data)\r\n");
      out.write("                {\r\n");
      out.write("                },//数据加载前\r\n");
      out.write("                onLoadError:function(data)\r\n");
      out.write("                {\r\n");
      out.write("                    $.messager.alert('系统提示', '抱歉，数据加载出错', 'info');\r\n");
      out.write("                },//数据加载出错\r\n");
      out.write("                onLoadSuccess:function(data)\r\n");
      out.write("                {\r\n");
      out.write("                    if (eval(data).rows[0].parameid==\"\") {\r\n");
      out.write("                        $('#ParameList').datagrid('deleteRow', 0);\r\n");
      out.write("                    }\r\n");
      out.write("                    //$.mask().hide();\r\n");
      out.write("                },//数据加载完闭\r\n");
      out.write("                url:'/Action/ParameWriter.do?pmark=list',\r\n");
      out.write("                idField:'parameid',\r\n");
      out.write("                columns:[[\r\n");
      out.write("                    {field:'parameid',title:'参数编号',width:70,align:'center'},\r\n");
      out.write("                    {field:'paramesm',title:'参数说明',width:480,align:'center'},\r\n");
      out.write("                    {field:'paramevalue',title:'参数值',width:470,align:'center'}\r\n");
      out.write("                ]],\r\n");
      out.write("                rowStyler: function (index, row) {\r\n");
      out.write("                    return 'height:28px;';\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        function DelUnit()\r\n");
      out.write("        {\r\n");
      out.write("            var selected = $('#ParameList').datagrid('getSelected');\r\n");
      out.write("            if (selected){\r\n");
      out.write("                $.messager.confirm('系统提示', '<span style=\"line-height: 20px;color: #FF0000;\">您确定要删除该参数吗?<br>删除之后有可能造成参数位置不准确,从而导至程序参数异常！</span>', function(r) {\r\n");
      out.write("                    if (r) {\r\n");
      out.write("                        if (selected.parameid==\"\") {\r\n");
      out.write("                            $.messager.alert('系统提示', '抱歉，请先选择一行数据', 'warning');\r\n");
      out.write("                            return false;\r\n");
      out.write("                        }\r\n");
      out.write("                        $.post('/Action/Parame.do?parameid='+selected.parameid+'&paramevalue='+selected.paramevalue+'&bid=");
      out.print(bid);
      out.write("&sid=");
      out.print(sid);
      out.write("&paramemethod=del', function(msg) {\r\n");
      out.write("                            var jsondata = eval('(' + msg + ')');\r\n");
      out.write("                            if (jsondata.err == \"\")//表示没有出错\r\n");
      out.write("                            {\r\n");
      out.write("                                $(\"#ParameList\").datagrid('load');\r\n");
      out.write("                            }\r\n");
      out.write("                            else\r\n");
      out.write("                            {\r\n");
      out.write("                                $.messager.alert('系统提示', jsondata.err, 'error');\r\n");
      out.write("                            }\r\n");
      out.write("                            //close();\r\n");
      out.write("                        });\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("            else\r\n");
      out.write("            {\r\n");
      out.write("                $.messager.alert('系统提示', '请先选择一行数据', 'info');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("<div region=\"center\" border=\"false\">\r\n");
      out.write("    <div class=\"datagrid-toolbar\" id='parame_toolbar'>\r\n");
      out.write("        <a id=\"reload\" href=\"javascript:void('');\" class=\"easyui-linkbutton\" plain=\"true\"\r\n");
      out.write("           data-options=\"iconCls:'icon-reload'\">刷新</a>\r\n");
      out.write("        ");

            if (! checkStr.isNull (UserProxy.UserOptProxy (request, UserProxyStr, "0")))
            {
        
      out.write("\r\n");
      out.write("        <a id=\"add\" href=\"javascript:void('');\" onclick=\"AddParame();\" class=\"easyui-linkbutton\" plain=\"true\" data-options=\"iconCls:'icon-add'\">新增</a>\r\n");
      out.write("        ");

            }
            if (! checkStr.isNull (UserProxy.UserOptProxy (request, UserProxyStr, "1")))
            {
        
      out.write("\r\n");
      out.write("        <a id=\"delete\" href=\"javascript:void('');\" onclick=\"DelUnit();\" class=\"easyui-linkbutton\" plain=\"true\" icon=\"icon-cancel\">删除</a>\r\n");
      out.write("        ");

            }
            if (! checkStr.isNull (UserProxy.UserOptProxy (request, UserProxyStr, "2")))
            {
        
      out.write("\r\n");
      out.write("        <a id=\"submit\" href=\"javascript:void('');\" onclick=\"EditParame();\" class=\"easyui-linkbutton\" plain=\"true\" icon=\"icon-edit\">修改</a>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <table id=\"ParameList\"></table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
