/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2015-09-28 13:44:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Ds_005fAdmin.sysset.parame;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Com.SysSetPackages.UserSetPackages.ProxyUserPackages.UserPurview;
import Com.SysSetPackages.UserSetPackages.ProxyUserPackages.ProxyUserPurview;
import Com.SharePackages.checkStr;

public final class parameedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Ds_Admin/include/userproxy.jsp", Long.valueOf(1417490842773L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      Com.SharePackages.Str_code_switch tostr = null;
      tostr = (Com.SharePackages.Str_code_switch) _jspx_page_context.getAttribute("tostr", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (tostr == null){
        tostr = new Com.SharePackages.Str_code_switch();
        _jspx_page_context.setAttribute("tostr", tostr, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

    String bid = tostr.to_utf_8 (request.getParameter ("bid"));
    String sid = tostr.to_utf_8 (request.getParameter ("sid"));
    UserPurview UserProxy = new ProxyUserPurview();
    String UserProxyStr = UserProxy.UserProxy (request);
    if (checkStr.isNull (UserProxyStr))
    {
        out.print("抱歉，您无权操作此模块");
        return;
    }

      out.write('\r');
      out.write('\n');

    String parameid=tostr.to_utf_8(request.getParameter("parameid"));
    if(!checkStr.checkIsNum(parameid))
    {
        out.print ("抱歉，缺少参数");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<title>参数修改</title>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/web.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/");
      out.print(checkStr.Parame(request,2));
      out.write("/easyui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/Ds_Admin/css/icon.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/jquery-1.4.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/validata.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/Ds_Admin/js/mask.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        $(function() {\r\n");
      out.write("            $('#form').form('load', '/Action/ParameWriter.do?pmark=mlist&parameid=");
      out.print(parameid);
      out.write("&random=' + Math.random());\r\n");
      out.write("            $('#save').bind(\"click\",function(){\r\n");
      out.write("                $('#form').form('submit', {\r\n");
      out.write("                    url:\"/Action/Parame.do\",\r\n");
      out.write("                    onSubmit: function(){\r\n");
      out.write("                        var flag = $(this).form('validate');\r\n");
      out.write("                        if (flag) {\r\n");
      out.write("                            $.mask();\r\n");
      out.write("                        }\r\n");
      out.write("                        return flag;\r\n");
      out.write("                    },\r\n");
      out.write("                    success:function(msg){\r\n");
      out.write("                        $.mask.hide();\r\n");
      out.write("                        var jsondata = eval('(' + msg + ')');\r\n");
      out.write("                        if (jsondata.err == \"\")//表示没有出错\r\n");
      out.write("                        {\r\n");
      out.write("                            $(window.parent.$('#gd').window('close'));\r\n");
      out.write("                            $(window.parent.$.messager.alert('系统提示', jsondata.msg, 'info'));\r\n");
      out.write("                            $(window.parent.$(\"#ParameList\").datagrid('reload'));\r\n");
      out.write("                        }\r\n");
      out.write("                        else {\r\n");
      out.write("                            $.messager.alert('系统提示', jsondata.err, 'error');\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<div region=\"north\" style=\"height:31px;overflow:hidden;\" split=\"false\" border=\"false\" >\r\n");
      out.write("\t\t<div class=\"datagrid-toolbar\">\r\n");
      out.write("            <a id=\"save\" icon=\"icon-save\" href=\"#\" class=\"easyui-linkbutton\" plain=\"true\" >修改</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <div region=\"center\" style=\"overflow:auto;padding:5px;\" border=\"false\">\r\n");
      out.write("       <form id=\"form\" method=\"post\">\r\n");
      out.write("           <table class=\"table-edit\"  width=\"98%\" align=\"center\">\r\n");
      out.write("           \t\t<tr class=\"title\"><td colspan=\"2\">参数信息</td></tr>\r\n");
      out.write("\r\n");
      out.write("\t           \t<tr><td style=\"width: 20%;text-align: right\">参数说明:</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                    <input type=\"hidden\" id=\"paramemethod\" name=\"paramemethod\" value=\"mod\"/>\r\n");
      out.write("                    <input type=\"hidden\" value=\"");
      out.print(bid);
      out.write("\" name=\"bid\"/>\r\n");
      out.write("                    <input type=\"hidden\" value=\"");
      out.print(sid);
      out.write("\" name=\"sid\"/>\r\n");
      out.write("                    <input type=\"hidden\" name=\"parameid\" value=\"");
      out.print(parameid);
      out.write("\"/>\r\n");
      out.write("                        <input type=\"text\" name=\"paramesm\" id=\"paramesm\" class=\"easyui-validatebox\"\r\n");
      out.write("                               data-options=\"required:true,\r\n");
      out.write("                           validType:'length[2,105]',\r\n");
      out.write("                           invalidMessage:'不能少于2个汉字',\r\n");
      out.write("                           missingMessage:'请至少输入2个汉字'\"\r\n");
      out.write("                               maxlength=\"105\" style=\"width: 320px;\"/>\r\n");
      out.write("                    </td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td style=\"text-align: right\">参数值:</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input type=\"text\" name=\"paramevalue\" id=\"paramevalue\"\r\n");
      out.write("                               class=\"easyui-validatebox\"\r\n");
      out.write("                               data-options=\"required:true,\r\n");
      out.write("                               invalidMessage:'不能少于1个字符',\r\n");
      out.write("                               missingMessage:'请至少输入1个字符'\"\r\n");
      out.write("                               style=\"width: 320px;\"/>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("           </table>\r\n");
      out.write("       </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
